name: dart_clean_arch
description: dart_clean_arch
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^2.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1

dependencies:
  crypto: ^3.0.2
  hive: ^2.1.0
  uuid: ^3.0.6
